### ISSUE TITLE
Why fork everything

### ISSUE THREAD

**Issue by mausch** [SolrNetLight/SolrNetLight#1]
While it's perfectly valid and ok to fork an open source project as a new one, I have to wonder why do it in this case instead of contributing to SolrNet to making it portable? SolrNet currently does all I need it to do so I'm not contributing new features personally too often, but I still review and merge pull requests from others, so it's not like it's unmaintained. I'd be open to reviewing any changes towards making SolrNet a PCL.

**Comment by dlamande** [comment]
Hi Mauricio,

We thought about contributing to SolrNet Project. But it was too difficult to migrate the existing source code into a portable class library(many lake of classes in pcl). Indeed,we have changed the data format exchange for JSON (better for rest serialization than xml, it is easier to adapt and maintain in a PCL). We also removed the WebAdapter. To use native .net Object to make request. The most important fact is to be able to query SolR server from any plateform (wpf, wp8, w8, asp.net, xamarin Android, xamarin Ios, ...)

For serialization/deserialization we used Json.net

That's the reasons why we have made a fork..

I Hope you understand our position and choice of making that fork.

At your disposal to aswer any question you may have.

(Hope you Will Win your semi final)

Envoyé à partir de mon Windows Phone

---

De : Mauricio Scheffermailto:notifications@github.com
Envoyé : ‎09/‎07/‎2014 17:30
À : SolrNetLight/SolrNetLightmailto:SolrNetLight@noreply.github.com
Objet : [SolrNetLight] Why fork everything (#1)

While it's perfectly valid and ok to fork an open source project as a new one, I have to wonder why do it in this case instead of contributing to SolrNet to making it portable? SolrNet currently does all _I_ need it to do so I'm not contributing new features personally too often, but I still review and merge pull requests from others, so it's not like it's unmaintained. I'd be open to reviewing any changes towards making SolrNet a PCL.

---

Reply to this email directly or view it on GitHub:
https://github.com/SolrNetLight/SolrNetLight/issues/1
